<?php

/**
 * Implements hook_menu().
 */
function anatomy_menu() {
  $items['admin/reports/anatomy'] = array(
    'title' => 'Anatomy',
    'page callback' => 'anatomy_page',
    'access arguments' => array('access anatomy'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'anatomy.inc',     // don't forget to add the file and path
    'file path' => drupal_get_path('module', 'anatomy'),
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function anatomy_permission() {
  return array(
    'access anatomy' => array(
      'title' => t('Access anatomy page'),
      'description' => t('Access anatomy page.'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function anatomy_theme() {
  return array(
    'anatomy' => array(
      'variables' => array(
        'data' => NULL,
      ),
      'template' => 'anatomy',
    ),
  );
}
